"""Create stock table

Revision ID: 15c1c2c055f4
Revises: 3dbcf94920ed
Create Date: 2022-06-05 00:59:06.196996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c1c2c055f4'
down_revision = '3dbcf94920ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Stock', sa.Column('qty', sa.Integer(), nullable=False))
    op.add_column('Stock', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('Stock', 'available',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Stock', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Stock', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('Stock', 'available',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Stock', 'updated_at')
    op.drop_column('Stock', 'qty')
    # ### end Alembic commands ###
