"""Create stock table

Revision ID: 1d5fd50d64c4
Revises: 15c1c2c055f4
Create Date: 2022-06-05 01:43:16.706225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d5fd50d64c4'
down_revision = '15c1c2c055f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
