"""Modified ralationship

Revision ID: 3dbcf94920ed
Revises: 
Create Date: 2022-06-04 23:12:21.443249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbcf94920ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('etag', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('everage_count', sa.Integer(), nullable=True),
    sa.Column('content_version', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=3), nullable=True),
    sa.Column('preview_link', sa.Text(), nullable=True),
    sa.Column('info_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='unique_component_commit')
    )
    op.create_table('Image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('small_thumbnail', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('small', sa.Text(), nullable=True),
    sa.Column('medium', sa.Text(), nullable=True),
    sa.Column('large', sa.Text(), nullable=True),
    sa.Column('extra_large', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['Book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Image')
    op.drop_table('Book')
    # ### end Alembic commands ###
