"""Modified table

Revision ID: 495950e86a0a
Revises: a0773d7859ab
Create Date: 2022-06-05 13:51:07.339888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495950e86a0a'
down_revision = 'a0773d7859ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
