"""Create Borrow_log table

Revision ID: 5669f7207245
Revises: 1d5fd50d64c4
Create Date: 2022-06-05 03:58:00.671616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5669f7207245'
down_revision = '1d5fd50d64c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Borrow_log', sa.Column('returned_at', sa.DateTime(), nullable=True))
    op.add_column('Borrow_log', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Borrow_log', 'Book', ['book_id'], ['id'])
    op.drop_column('Borrow_log', 'return_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Borrow_log', sa.Column('return_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Borrow_log', type_='foreignkey')
    op.drop_column('Borrow_log', 'book_id')
    op.drop_column('Borrow_log', 'returned_at')
    # ### end Alembic commands ###
